### ISSUE TITLE
Chapter 3.2.3 Adding the bootstrap

### ISSUE THREAD

**Issue by FredHasselot** [danielschmitz/angular2-codes#1]
Hi, i added : `<link rel="steelsheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css" >` to index.html

When i watch the source code generated by the browser i can see the css file but bootstrap's classes are not applied.

Any idea ? 

Thanks

**Comment by danielschmitz** [comment]
Hi, 

sorry, see your issue only today :(

please zip your code and send to danieljfa at gmail dot com
