### ISSUE TITLE
Link problem with ebook

### ISSUE THREAD

**Issue by pablorsk** [danielschmitz/angular2-codes#2]
We buy your book, ITS AWESOME!

Just a tip: fix the link on readme, we believe no one can lost this excelente book.

**Comment by danielschmitz** [comment]
Hi

thanks!

can i insert your comment in my Testimonials page?

**Comment by pablorsk** [comment]
Off course! Feel free to correct my bad English.

**Comment by danielschmitz** [comment]
tks!
